### ISSUE TITLE
Syncavatar

### ISSUE THREAD

**Issue by drogs** [veldlabs/miki-bot#161]
![discord_2017-06-01_03-19-21](https://cloud.githubusercontent.com/assets/26911525/26668783/40d0ab2c-4679-11e7-9f4c-4eaedb25d36f.png)

> at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Miki.Modules.AccountsModule.<>c.<<LoadEvents>b__0_35>d.MoveNext() in C:\Users\Veld\Documents\miki-sourcecode\Miki\Modules\AccountsModule.cs:line 714
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IA.Events.RuntimeCommandEvent.<TryProcessCommand>d__22.MoveNext() in C:\Users\Veld\Documents\IA\IA\Events\RuntimeCommandEvent.cs:line 135

**Comment by velddev** [comment]
I have yet to migrate the server files for the website
