### ISSUE TITLE
>help marry Doesn't work

### ISSUE THREAD

**Issue by Bejebajay** [veldlabs/miki-bot#168]
"  You used the 'help' and it crashed!
Please screenshot this message and send it to the miki issue page (https://github.com/velddev/miki/issues)
Error Message
Value cannot be null.
Parameter name: format
Error Log
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Miki.Languages.Locale.GetString(String m, Object[] p) in C:\Users\Veld\Documents\miki-sourcecode\Miki\Languages\LocaleStrings.cs:line 76
   at Miki.Modules.GeneralModule.<>c__DisplayClass0_2.<<LoadEvents>b__16>d.MoveNext() in C:\Users\Veld\Documents\miki-sourcecode\Miki\Modules\GeneralModule.cs:line 250
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IA.Events.RuntimeCommandEvent.<TryProcessCommand>d__22.MoveNext() in C:\Users\Veld\Documents\IA\IA\Events\RuntimeCommandEvent.cs:line 135
Did you not want this message? use `>toggleerrors` to disable it!  "

**Comment by NovieCat** [comment]
>help give did the same:
You used the 'help' and it crashed!
Please screenshot this message and send it to the miki issue page (https://github.com/velddev/miki/issues)
Error Message
Value cannot be null.
Parameter name: format
Error Log
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Miki.Languages.Locale.GetString(String m, Object[] p) in C:\Users\Veld\Documents\miki-sourcecode\Miki\Languages\LocaleStrings.cs:line 78
   at Miki.Modules.GeneralModule.<>c__DisplayClass0_2.<<LoadEvents>b__16>d.MoveNext() in C:\Users\Veld\Documents\miki-sourcecode\Miki\Modules\GeneralModule.cs:line 250
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IA.Events.RuntimeCommandEvent.<TryProcessCommand>d__22.MoveNext() in C:\Users\Veld\Documents\IA\IA\Events\RuntimeCommandEvent.cs:line 135
Did you not want this message? use `>toggleerrors` to disable it!

**Comment by velddev** [comment]
The help<arg> is currently in a slight odd state because of localisation.

**Comment by LovingMelody** [comment]
I'm guessing this is the cause of #135 ?
