### ISSUE TITLE
slots error

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#171]
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at Miki.Modules.FunModule.<>c.<<LoadEvents>b__0_38>d.MoveNext() in C:\Users\Veld\Documents\miki-sourcecode\Miki\Modules\FunModule.cs:line 576
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IA.Events.RuntimeCommandEvent.<TryProcessCommand>d__22.MoveNext() in C:\Users\Veld\Documents\IA\IA\Events\RuntimeCommandEvent.cs:line 135

**Comment by velddev** [comment]
You have to add a number on the back of the slots command.
