### ISSUE TITLE
Miki said to tell you this. Error when >pasta search without keyword

### ISSUE THREAD

**Issue by The-Sound** [veldlabs/miki-bot#95]
at System.String.Substring(Int32 startIndex, Int32 length)
   at Miki.Modules.PastaModule.<<LoadEvents>b__0_2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IA.Events.RuntimeCommandEvent.<TryProcessCommand>d__22.MoveNext()

![image](https://cloud.githubusercontent.com/assets/24360204/25412452/178579b8-2a23-11e7-9a92-a5a6f5c215b0.png)

**Comment by velddev** [comment]
Thanks I'l fix this in the next patch!

**Comment by velddev** [comment]
Which is literally in a few minutes <3

**Comment by velddev** [comment]
Fixed for 0.2.2
